
[[constraint]]
  name = "github.com/andygrunwald/go-jira"
  version = "1.0.0"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.11"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
